In [1]:
import efmtool
import numpy as np
import pandas as pd

In [4]:
options = efmtool.get_default_options()
options['level'] = 'WARNING'

Let's say we have two ECMs (only one per species).
Species 1 takes up A and secretes B, species 2 takes up B and secretes C. 
Now to calculaate community modes, we can place them in one matrix and calculate EFMs with EFMtool.
However, notice that if you just put the ECMs together (the first two columns), the systems could not be in steady state - we need to add the community exchange reactions - columns SA, SB and SC.
SA is reversible (indicated by '1' in the list of reversibilities `revs`) because it can be take up from the medium. B and C are not in the medium so they can only be secreted and therefore ar irreversible.

In [5]:
matrix = np.array([[-1, 0, -1, 0, 0],
                   [1, -1, 0, -1, 0],
                   [0, 1, 0, 0, -1]])
revs = [0,0,1,0,0]
mets = ["A", "B", "C"]
rxns = ["ECM1", "ECM2", "SA", "SB", "SC"]

In [7]:
cefms = efmtool.calculate_efms(matrix, revs, rxns, mets, options)
cefms = pd.DataFrame(cefms, index = rxns)
cefms

        0    1
ECM1  1.0  1.0
ECM2  0.0  1.0
SA   -1.0 -1.0
SB    1.0  0.0
SC    0.0  1.0

We get two community modes. One when only species 1 is present and A is converted to B and the other one where we have both species and the community converts A all the way to C.
Now, to recover the relative abundances, we need to normalize the sum of the ECMs to 1.

In [ ]:
# divide by the sum of the ECMs to get abundances

Now  a more complicated example where species 1 has two ECMs.

In [8]:
matrix = np.array([[-1, -1, 0, -1, 0, 0],
                   [1, 0.5, -1, 0, -1, 0],
                   [0, 0.5, 1, 0, 0, -1]])
revs = [0,0,0,1,0,0]
mets = ["A", "B", "C"]
rxns = ["ECM11", "ECM12", "ECM2", "SA", "SB", "SC"]

In [9]:
efms = efmtool.calculate_efms(matrix, revs, rxns, mets, options)
pd.DataFrame(efms, index = rxns)

         0    1    2    3
ECM11  1.0  0.0  1.0  0.0
ECM12  0.0  2.0  0.0  2.0
ECM2   0.0  0.0  1.0  1.0
SA    -1.0 -2.0 -1.0 -2.0
SB     1.0  1.0  0.0  0.0
SC     0.0  1.0  1.0  2.0

In [ ]:
# divide by the sum of the ECMs to get abundances